name              = "portfolio"
compatibility_date = "2025-06-22"
workers_dev       = true
account_id        = "48110e05664b089f3c8482942693bd66"

# No more `type = "site"` at top level! Wrangler infers a site
# whenever you have a [site] table.

[site]
  # directory is where your static assets live:
  # if your index.html is in the repo root, point to "."
  directory = "."
